# entering 47 values into ignition tables per row, each of these values should line up to an existing datapoint in SQL
# match each of these lines to a item of data & connect to db outside of loop and commit one row at a time in sync with the csvwriter --> if it fails it could halt the CSV write job so make sure to handle that one
query_stmt = """
    INSERT INTO fiber_yield (
        spool_id,
        count,
        raw_start_time,
        week,
        line_id,
        material_id,
        run_length,
        run_time,
        raw_finish_time,
        gm_unpadded_yield,
        gm_unpadded_count,
        pad_bad_yield,
        pad_bad_count,
        remove_short_bad_yield,
        remove_short_bad_count,
        gm_gp_yield,
        gm_gp_count,
        respooled_yield,
        binned_respooled_count,
        binned_respooled_yield,
        respooled_count,
        50cc_eq_produced,
        150cc_eq_produced,
        respooled_150_count,
        150cc_yield,
        respool_instr,
        XY_mean_good,
        XY_std_good,
        XY_mean_all,
        XY_std_all,
        XX_mean_good,
        XX_std_good,
        XX_mean_all,
        XX_std_all,
        YY_mean_good,
        YY_std_good,
        YY_mean_all,
        YY_std_all,
        minarea1m_loss,
        maxarea1m_loss,
        x_minareasingleaxis1m_loss,
        x_maxareasingleaxis1m_loss,
        y_minareasingleaxis1m_loss,
        y_maxareasingleaxis1m_loss,
        minarea20m_loss,
        maxarea20m_loss,
        qcstatus,    
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    ON DUPLICATE KEY UPDATE
        spool_id = VALUES(spool_id),
        count = VALUES(count),
        raw_start_time = VALUES(raw_start_time),
        week = VALUES(week),
        line_id = VALUES(line_id),
        material_id = VALUES(material_id),
        run_length = VALUES(run_length),
        run_time = VALUES(run_time),
        raw_finish_time = VALUES(raw_finish_time),
        gm_unpadded_yield = VALUES(gm_unpadded_yield),
        gm_unpadded_count = VALUES(gm_unpadded_count),
        pad_bad_yield = VALUES(pad_bad_yield),
        pad_bad_count = VALUES(pad_bad_count),
        remove_short_bad_yield = VALUES(remove_short_bad_yield),
        remove_short_bad_count = VALUES(remove_short_bad_count),
        gm_gp_yield = VALUES(gm_gp_yield),
        gm_gp_count = VALUES(gm_gp_count),
        respooled_yield = VALUES(respooled_yield),
        binned_respooled_count = VALUES(binned_respooled_count),
        binned_respooled_yield = VALUES(binned_respooled_yield),
        respooled_count = VALUES(respooled_count),
        50cc_eq_produced = VALUES(50cc_eq_produced),
        150cc_eq_produced = VALUES(150cc_eq_produced),
        respooled_150_count = VALUES(respooled_150_count),
        150cc_yield = VALUES(150cc_yield),
        respool_instr = VALUES(respool_instr),
        XY_mean_good = VALUES(XY_mean_good),
        XY_std_good = VALUES(XY_std_good),
        XY_mean_all = VALUES(XY_mean_all),
        XY_std_all = VALUES(XY_std_all),
        XX_mean_good = VALUES(XX_mean_good),
        XX_std_good = VALUES(XX_std_good),
        XX_mean_all = VALUES(XX_mean_all),
        XX_std_all = VALUES(XX_std_all),
        YY_mean_good = VALUES(YY_mean_good),
        YY_std_good = VALUES(YY_std_good),
        YY_mean_all = VALUES(YY_mean_all),
        YY_std_all = VALUES(YY_std_all),
        minarea1m_loss = VALUES(minarea1m_loss),
        maxarea1m_loss = VALUES(maxarea1m_loss),
        x_minareasingleaxis1m_loss = VALUES(x_minareasingleaxis1m_loss),
        x_maxareasingleaxis1m_loss = VALUES(x_maxareasingleaxis1m_loss),
        y_minareasingleaxis1m_loss = VALUES(y_minareasingleaxis1m_loss),
        y_maxareasingleaxis1m_loss = VALUES(y_maxareasingleaxis1m_loss),
        minarea20m_loss = VALUES(minarea20m_loss),
        maxarea20m_loss = VALUES(maxarea20m_loss),
        qcstatus = VALUES(qcstatus),
"""

# date = VALUES(date),
# shift = VALUES(shift),
# line = VALUES(line),
# material_id = VALUES(material_id)