export const lineColor = {
  "EX00" : "#ff6f00",
  "EX01" : "#aaff00",
  "EX02" : "#00ffb3",
  "EX03" : "#0077ff",
  "EX04" : "#cc00ff",
}


export const materialColor = {
    "316": "#00B5E2",
    "ES2": "#00BDD2",
    "ONX": "#757575", // "#1F1F1F"
    "OXL": "#6a6a6a",
    "D2S": "#169C38",
    "CPR": "#B24A00",
    "OFR": "#CF4520",
    "17F": "#2053B2",
    "FIB": "#cacaca",
    "KEV": "#cacaca",
    "CAR": "#cacaca",
    "HST": "#cacaca",
    "625": "#47169C",
    "G16" :"#D8D0C1",
    "172" : "#3333FF",
    "CFA" : "#cacaca",
    "CFU" : "#cacaca",
    "174" : "#497eb8",
    "820" : "#ffe100",
    "AO1" : "#e9edf7",
    "D20" : "#7ec193",
    "DTS" : "#7ec193",
    "ESD" : "##047cc9",
    "OFA" : "#D2451E",
    "H13" : "#fd6e4c",
    "HTS" : "#DA291C",
    "PFR" : "#ff753a",
    "RDM" : "#ffe600",
    "RDP" : "#ffe600",
    "VGA" : "#2E2259",
    "T64" : "#cccccc",
    "17P" : "#497eb8"
  };

export const translateCompounding = {
  "D2S" : "DTP",
  "31P" : "316",
  "HTP" : "HTS",
  "CPP" : "CPR",
  // sswap
  "DTP" : "D2S",
  "316" : "31P",
  "HTS" : "HTP",
  "CPR" : "CPP",

}

export const materialDict = {
  "ONX": "Onyx",
  "G16": "G16 Nylon",
  "1J1": "1J1 1Kg",
  "5J1": "5J1 5Lb",
  "820": "820 80-20",
  "KEV": "KEV Continuous Kevlar Fiber",
  "OXP": "OXP Onyx Pellets",
  "G1P": "G16 Nylon Pellets",
  "82P": "80-20 Pellets",
  "CAR": "Continuous Carbon Fiber",
  "HST": "High Strength High Temperature Fiberglass",
  "FIB": "Continuous Fiberglass",
  "NYP": "CV140 Nylon Pellets",
  "NYW": "Nylon - White",
  "174": "17-4PH Stainless Steel",
  "316": "316L Stainless Steel",
  "625": "Inconel 625",
  "A20": "A2 Tool Steel",
  "AO1": "A01 Ceramic Release",
  "H13": "H13 Tool Steel",
  "OFR": "Onyx FR",
  "D20": "D2 Tool Steel",
  "CPR": "Copper O65HW",
  "PFR": "Flame Retardant Prepreg Plastic",
  "RCF": "Raw Carbon Fiber",
  "RKV": "Raw Kevlar",
  "RFB": "Raw Fiberglass",
  "CFA": "Carbon Fiber FR-A",
  "OFA": "Onyx FR - A",
  "17P": "17-4 PH Stainless Steel Pellets",
  "31P": "316L Stainless Steel Pellets",
  "62P": "625 Inconel Pellets",
  "A2P": "A2 Tool Steel Pellets",
  "A0P": "A01 Ceramic Release Pellets",
  "H1P": "H13 Tool Steel Pellets",
  "OFP": "Onyx FR Pellets",
  "D2P": "D2 Tool Steel Pellets",
  "CPP": "Copper O65HW Pellets",
  "PFP": "Prepreg Plastic FR Pellets",
  "J1F": "J1 Plastic Filament",
  "ESD": "Onyx ESD",
  "ESP": "Onyx ESD Pellets",
  "RDF": "R&D Fiber",
  "17F": "17-4PH Flex",
  "CFU": "HIGH TEMPERATURE CARBON FIBER",
  "UL1": "Ultem 1010",
  "OXL": "Onyx XL",
  "HTS": "H13 V2",
  "UL9": "ULTEM 9085 Filament",
  "ULS": "Support for ULTEM Filament",
  "DTS": "D2 V2",
  "DTP": "D2 V2 Pellets",
  "HTP": "H13 V2 Pellets",
  "7FP": "174 V2 Pellets",
  "VGA": "Vega",
  "VGP": "Vega (PEKK) Pellets",
  "TPU": "TPU",
  "PLA": "PLA",
  "CHT": "HIGH TEMPERATURE CARBON FIBER",
  "ES2": "Onyx ESD V2",
  "NYF": "Nylon - White Food Safe",
  "RDP": "R&D Pellets",
  "T64" : "Titanium",
};
